### ISSUE TITLE
Automatic shutdown on stall

### ISSUE THREAD

**Issue by RoyCurtis** [Gamealition/ForgeAutoShutdown#2]
@Meow-J [suggested automatically shutting down the server on stall](http://minecraft.curseforge.com/mc-mods/231774-forgeautoshutdown?comment=8). Recently, Gamealition FTB has been experiencing this issue also, so this is a good idea to implement.

**Comment by Meow-J** [comment]
Actually, I have another idea: *Add an option to shutdown the server when tps is lower than a certain value.* It should be easy after adding a watchdog, which you may need in stall detection.

**Comment by RoyCurtis** [comment]
Hmm; I could add that in also, but I think it would be best if it only shutdown after the TPS lingered below a threshold. For example, if it stayed below 5 TPS for more than 60 seconds. Triggering a shutdown instantly on low TPS may result in a lot of false positives.

**Comment by Meow-J** [comment]
Yes, that's what I meant

**Comment by RoyCurtis** [comment]
Writing up how I have implemented this idea in [`WatchdogTask.java`](https://github.com/Gamealition/ForgeAutoShutdown/blob/master/src/main/java/roycurtis/autoshutdown/WatchdogTask.java):

The watchdog is a timer task; it runs on a separate thread and makes it a reliable method of monitoring the server (or technically, the *main server thread*).

Every call in the task is considered carefully, to make sure it cannot crash the server with unsafe cross-thread operations (e.g. `MathHelper.average(SERVER.tickTimeArray)`, while not accurate concurrently, is fine to do).

The timer task is run at an interval of seconds (10, by default). Every time it does so:

1. It compares the current number of server ticks with the previously recorded value. If they are the same, the server is considered  "hanging"
2. Else, it checks if the current TPS is below a threshold. If so, it keeps track of how many timer ticks it stays low. If this continues past a configured timeout, the server is killed. If the TPS goes back above the threshold, the tick counter is reset.

If the server is considered "hanging", then the timer task behaves differently:

1. If the number of server ticks remain the same past a configured timeout, the server is killed
2. Else, the server is no longer considered "hanging"

When the server is killed by either scenario:

1. If configured, a soft kill will be attempted first. It spawns a new thread; if the server is still alive in 10 seconds, the thread triggers a hard kill. Then the runtime is stopped via Forge, which (at least in 1.7.10) MinecraftServer responds to by shutting down the server gracefully.
2. A hard kill asks Forge to halt the runtime, which is expected to be instant and fail-safe

----

Before I can close this, I need to make sure this works as expected in a production environment. 

Whilst testing on a Forge server with no other mods, the hang timers and automatic kills worked well and saved the worlds. But on a complex server with 100+ mods (like DW20), there could be mods that have a shutdown hook or could delay/hang the saving process.

I will be testing this over the coming week, but I will also upload a release on here and CurseForge. I also need to port the changes to 1.8.

Thank you very much for this suggestion, @Meow-J

**Comment by Meow-J** [comment]
Thank you for your work. I'll test it on my server later

**Comment by Meow-J** [comment]
Works on my server
```
[23:07:10] [Sampler watchdog thread/WARN]: The watchdog detected that execution has been stalled for 30000 ms.
[23:07:11] [Sampler watchdog thread/INFO]: Stall report created at ./stall-reports/stall-2015-08-07_23.07.10.txt.
[23:07:28] [ForgeAutoShutdown watchdog/WARN]: Server is hung on a tick after 40 seconds
[23:07:28] [ForgeAutoShutdown watchdog/WARN]: Attempting a soft kill of the server...
[23:07:28] [ForgeAutoShutdown watchdog/INFO]: Java has been asked to exit (code 1) by cpw.mods.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:634).
[23:07:28] [ForgeAutoShutdown watchdog/INFO]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called
```

**Comment by RoyCurtis** [comment]
Nice to see! Thanks. Actually, I will go ahead and consider that an assuring success. Good too that Sampler was able to generate a report before the shutdown.
